<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:variable name="initial_bottom_pos">24.5</xsl:variable>
	<xsl:variable name="initial_left_pos">1</xsl:variable>
	<xsl:variable name="height_increment">1.8</xsl:variable>
	<xsl:variable name="width_increment">11</xsl:variable>
	<xsl:variable name="frame_height">5cm</xsl:variable>
	<xsl:variable name="frame_width">15cm</xsl:variable>
	<xsl:variable name="number_columns">1</xsl:variable>
	<xsl:variable name="max_frames">21</xsl:variable>

	<xsl:template match="/">
		<xsl:apply-templates select="menifest"/>
	</xsl:template>

	<xsl:template match="menifest">
		<document>
			<template leftMargin="2.0cm" rightMargin="2.0cm" topMargin="2.0cm" bottomMargin="2.0cm" title="Menifest" author="Generated by Open ERP">
				<pageTemplate id="all">
					<pageGraphics/>
					<xsl:apply-templates select="menifest-line" mode="frames"/>
				</pageTemplate>
			</template>
			<stylesheet>
				<paraStyle name="nospace" fontName="Courier" fontSize="7" spaceBefore="0" spaceAfter="0"/>
			</stylesheet>
			<story>
				<xsl:apply-templates select="menifest-line" mode="story"/>
			</story>
		</document>
	</xsl:template>

	<xsl:template match="menifest-line" mode="frames">
		<xsl:if test="position() &lt; $max_frames + 1">
			<frame>
				<xsl:attribute name="width">
					<xsl:value-of select="$frame_width"/>
				</xsl:attribute>
				<xsl:attribute name="height">
					<xsl:value-of select="$frame_height"/>
				</xsl:attribute>
				<xsl:attribute name="x1">
					<xsl:value-of select="$initial_left_pos + ((position()-1) mod $number_columns) * $width_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
				<xsl:attribute name="y1">
					<xsl:value-of select="$initial_bottom_pos - floor((position()-1) div $number_columns) * $height_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
			</frame>
		</xsl:if>
	</xsl:template>

	<xsl:template match="menifest-line" mode="story">
	    <spacer length="0.3cm"/>
	    <barCode><xsl:value-of select="name"/></barCode>
		<para style="nospace"><xsl:value-of select="name"/><xsl:text>, </xsl:text><xsl:value-of select="date"/><xsl:text>,</xsl:text><xsl:value-of select="agency"/></para>
		<para style="nospace">
	        <xsl:choose>
	            <xsl:when test="count(sales) >= 1">
	                <xsl:apply-templates select="sales"/>
	            </xsl:when>
	            <xsl:otherwise>
	                <xsl:apply-templates select="sales"/>
	            </xsl:otherwise>
	        </xsl:choose>
	    </para>
	</xsl:template>
	
	<xsl:template match="sales">
        <xsl:value-of select="sale_name"/><xsl:text>(</xsl:text><xsl:value-of select="amount_total"/><xsl:text>),</xsl:text>
    </xsl:template>
</xsl:stylesheet>
